version: "3.7"

services:
  deophp:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: php
    volumes:
      - .:/var/www
    env_file:
      - .docker.env

  database:
    env_file:
      - .docker.env
    container_name: database
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
  api:
    image: nginx:stable-alpine
    container_name: api
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - deophp
      - database

  rabbit:
    image: "rabbitmq:3-management"
    env_file:
      - .docker.env
    ports:
      - "5672:5672"

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    container_name: worker
    volumes:
      - .:/var/www
      - ./supervisord.conf:/etc/supervisord.conf
    env_file:
      - .docker.env
    depends_on:
      - deophp
    command: ["supervisord", "-c",  "/etc/supervisord.conf"]

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - 8003:8080
    volumes:
      - ./openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json

volumes:
  dbdata: