version: "3.7"

services:
  deophp:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: php
    volumes:
      - .:/var/www
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: deotrans
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      MAIL_HOST: 
      MAIL_PORT: 587
      MAIL_USERNAME: 
      MAIL_PASSWORD: 
      MAIL_ENCRYPTION: tls
      MAIL_FROM: adhityoradeon@gmail.com
      MAIL_FROM_NAME: "Agam Adhityo"
      RABBIT_HOST: rabbit
      RABBIT_PORT: 5672
      RABBIT_USER: rabbitmq
      RABBIT_PASSWORD: rabbitmq
      RABBIT_VHOST: "/"

  database:
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deotrans
    container_name: database
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
  api:
    image: nginx:stable-alpine
    container_name: api
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - deophp
      - database

  rabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    container_name: worker
    volumes:
      - .:/var/www
      - ./supervisord.conf:/etc/supervisord.conf
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: deotrans
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      MAIL_HOST: 
      MAIL_PORT: 587
      MAIL_USERNAME: 
      MAIL_PASSWORD: 
      MAIL_ENCRYPTION: tls
      MAIL_FROM: adhityoradeon@gmail.com
      MAIL_FROM_NAME: "Agam Adhityo"
      RABBIT_HOST: rabbit
      RABBIT_PORT: 5672
      RABBIT_USER: rabbitmq
      RABBIT_PASSWORD: rabbitmq
      RABBIT_VHOST: "/"
    depends_on:
      - deophp
    command: ["supervisord", "-c",  "/etc/supervisord.conf"]

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - 8003:8080
    volumes:
      - ./openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json

volumes:
  dbdata: